export const GAME_BACKLOG_SORT_ALL = "GAME_BACKLOG_SORT_ALL";
export const GAME_BACKLOG_SORT_LOCKED = "GAME_BACKLOG_SORT_LOCKED";
export const GAME_BACKLOG_SORT_UNLOCKED = "GAME_BACKLOG_SORT_UNLOCKED";
export const GAME_BACKLOG_SORT_PINNED = "GAME_BACKLOG_SORT_PINNED";

export const GAME_BACKLOG_FILTER_ALL = "GAME_BACKLOG_FILTER_ALL";
export const GAME_BACKLOG_FILTER_BRONZE = "GAME_BACKLOG_FILTER_BRONZE";
export const GAME_BACKLOG_FILTER_COMMON = "GAME_BACKLOG_FILTER_COMMON";
export const GAME_BACKLOG_FILTER_RARE = "GAME_BACKLOG_FILTER_RARE";
export const GAME_BACKLOG_FILTER_EPIC = "GAME_BACKLOG_FILTER_EPIC";
export const GAME_BACKLOG_FILTER_LEGENDARY = "GAME_BACKLOG_FILTER_LEGENDARY";
export const GAME_BACKLOG_FILTER_MARVEL = "GAME_BACKLOG_FILTER_MARVEL";

export const GAME_UNLOCK_TYPE_TODAY = "GAME_UNLOCK_TYPE_TODAY";
export const GAME_UNLOCK_TYPE_WEEK = "GAME_UNLOCK_TYPE_WEEK";
export const GAME_UNLOCK_TYPE_MONTH = "GAME_UNLOCK_TYPE_MONTH";
