export const GAME_BACKLOG_SORT_ALL = "GAME_BACKLOG_SORT_ALL";
export const GAME_BACKLOG_SORT_LOCKED = "GAME_BACKLOG_SORT_LOCKED";
export const GAME_BACKLOG_SORT_UNLOCKED = "GAME_BACKLOG_SORT_UNLOCKED";
export const GAME_BACKLOG_SORT_PINNED = "GAME_BACKLOG_SORT_PINNED";

export const GAME_BACKLOG_FILTER_ALL = "GAME_BACKLOG_FILTER_ALL";
export const GAME_BACKLOG_FILTER_BRONZE = "GAME_BACKLOG_FILTER_BRONZE";
export const GAME_BACKLOG_FILTER_COMMON = "GAME_BACKLOG_FILTER_COMMON";
export const GAME_BACKLOG_FILTER_RARE = "GAME_BACKLOG_FILTER_RARE";
export const GAME_BACKLOG_FILTER_EPIC = "GAME_BACKLOG_FILTER_EPIC";
export const GAME_BACKLOG_FILTER_LEGENDARY = "GAME_BACKLOG_FILTER_LEGENDARY";
export const GAME_BACKLOG_FILTER_MARVEL = "GAME_BACKLOG_FILTER_MARVEL";

export const GAME_UNLOCK_TYPE_TODAY = "GAME_UNLOCK_TYPE_TODAY";
export const GAME_UNLOCK_TYPE_WEEK = "GAME_UNLOCK_TYPE_WEEK";
export const GAME_UNLOCK_TYPE_MONTH = "GAME_UNLOCK_TYPE_MONTH";
export const GAME_UNLOCK_TYPE_ALL = "GAME_UNLOCK_TYPE_ALL";

export const PHASE_ALL = "PHASE_ALL";
export const PHASE_STORY = "PHASE_STORY";
export const PHASE_EASY = "PHASE_EASY";
export const PHASE_MISSABLE = "PHASE_MISSABLE";
export const PHASE_COLLECTIBLE = "PHASE_COLLECTIBLE";
export const PHASE_GRIND = "PHASE_GRIND";
export const PHASE_HARD = "PHASE_HARD";
export const PHASE_ONLINE = "PHASE_ONLINE";

export const PHASE_ALL_TITLE = "UNTAGGED";
export const PHASE_STORY_TITLE = "STORY";
export const PHASE_EASY_TITLE = "EASY";
export const PHASE_MISSABLE_TITLE = "MISSABLE";
export const PHASE_COLLECTIBLE_TITLE = "COLLECTIBLE";
export const PHASE_GRIND_TITLE = "GRIND";
export const PHASE_HARD_TITLE = "HARD";
export const PHASE_ONLINE_TITLE = "ONLINE";
