export const FETCH_ALL_GAMES_REQUEST = "FETCH_ALL_GAMES_REQUEST";
export const FETCH_ALL_GAMES_SUCCESS = "FETCH_ALL_GAMES_SUCCESS";
export const FETCH_ALL_GAMES_FAILURE = "FETCH_ALL_GAMES_FAILURE";

export const CHANGE_THEME_ID = "CHANGE_THEME_ID";
export const SET_SELECTED_GAME = "SET_SELECTED_GAME";

export const SET_HIDDEN_DESC_GAME = "SET_HIDDEN_DESC_GAME";

export const GAME_BACKLOG_SORT_CHANGE = "GAME_BACKLOG_SORT_CHANGE";
export const GAME_BACKLOG_FILTER_CHANGE = "GAME_BACKLOG_FILTER_CHANGE";
export const GAME_UNLOCKED_TYPE_CHANGE = "GAME_UNLOCKED_TYPE_CHANGE";

export const GAME_ADD_ACHIEVEMENT_PHASE = "GAME_ADD_ACHIEVEMENT_PHASE";
